version: "3"
services:
  spring :
    container_name: hhy_was
    image: zpzgzerg/docker_hhy
    expose:
      - 8080
    depends_on:
      - mysql
    networks:
      - hhy_net
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
  nginx:
    container_name: hhy_web
    image: zpzgzerg/docker-hhy-nginx
    ports:
      - 80:80
    volumes:
      - ~/docker_web/nginx/log/:/var/log/nginx/
    restart: always
    networks:
      - hhy_net
    depends_on:
      - spring
networks:
  hhy_net: