version: "3"
services:
  mysql:
    container_name: hhy_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: hhy
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ~/docker_db/mysql:/var/lib/mysql
    networks:
      - hhy_net
  spring :
    container_name: hhy_was
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on:
      - mysql
    networks:
      - hhy_net
  nginx:
    container_name: hhy_web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ~/docker_web/nginx/log/:/var/log/nginx/
    restart: always
    networks:
      - hhy_net
    depends_on:
      - spring
networks:
  hhy_net: